### ISSUE TITLE
Error: Failed to install provider on v0.3.1

### ISSUE THREAD

**Issue by Sebelino** [sethvargo/terraform-provider-googlecalendar#6]
Getting this error message when following the instructions in the readme:
```
$ terraform init
Error: Failed to install provider

Error while installing sethvargo/googlecalendar v0.3.1: could not query
provider registry for registry.terraform.io/sethvargo/googlecalendar: failed
to retrieve authentication checksums for provider: 404 Not Found
```
However, downgrading the version in `required_providers` from `~> 0.3` to `~> 1.7.1` fixed it.
```
$ terraform version
Terraform v0.14.11
```

**Comment by sethvargo** [comment]
Going from 0.3 -> 1.7 is an _upgrade_. This is intended with recent module registry changes as I understand.

**Comment by Sebelino** [comment]
@sethvargo That was a typo on my part; I meant 0.1.7, not 1.7.1. That is the only version found under Releases.

In any case, with the current instructions in `README.md`, `terraform init` will fail.
